USE [master]
GO

/****** Object:  Database [parcial ]    Script Date: 08/05/2025 21:49:07 ******/
CREATE DATABASE [parcial ]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'parcial', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\parcial .mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'parcial _log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\parcial _log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [parcial ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [parcial ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [parcial ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [parcial ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [parcial ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [parcial ] SET ARITHABORT OFF 
GO

ALTER DATABASE [parcial ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [parcial ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [parcial ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [parcial ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [parcial ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [parcial ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [parcial ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [parcial ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [parcial ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [parcial ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [parcial ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [parcial ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [parcial ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [parcial ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [parcial ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [parcial ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [parcial ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [parcial ] SET RECOVERY FULL 
GO

ALTER DATABASE [parcial ] SET  MULTI_USER 
GO

ALTER DATABASE [parcial ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [parcial ] SET DB_CHAINING OFF 
GO

ALTER DATABASE [parcial ] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [parcial ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [parcial ] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [parcial ] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [parcial ] SET QUERY_STORE = ON
GO

ALTER DATABASE [parcial ] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [parcial ] SET  READ_WRITE 
GO


USE [parcial ]
GO

/****** Object:  Table [dbo].[productos]    Script Date: 08/05/2025 21:49:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[productos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [nvarchar](50) NOT NULL,
	[precio] [decimal](10, 2) NOT NULL,
	[unidades] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [parcial ]
GO

INSERT INTO [dbo].[productos]
           ([nombre]
           ,[precio]
           ,[unidades])
     VALUES
           ('Switch 8 Puertos'
           ,750.00
           ,3)
GO
INSERT INTO [dbo].[productos]
           ([nombre]
           ,[precio]
           ,[unidades])
     VALUES
           ('Impresora Multifuncional'
           ,950.00
           ,5)
GO
INSERT INTO [dbo].[productos]
           ([nombre]
           ,[precio]
           ,[unidades])
     VALUES
           ('Memoria USB 16 GB'
           ,4.50
           ,20)
GO
